
INSERT  INTO `sys_purview`(`PURVIEW_ID`,`NAME`,`CODE`,`PARENT_ID`,`CREATE_TIME`,`UPDATE_TIME`,`DELETE_STATE`,`NOTES`) VALUES 
(38,'资源预览','RES_PREVIEW',3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,NULL); 
(317,'资源制作-上传资源预览文件','RES_PREVIEW_UPLOAD',31,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,NULL);

/*增加两个字段，保存内网、外网 下载预览文件的地址*/
ALTER TABLE `r_book_res` ADD `PREVIEW_ADDR_IN_NET` TEXT;
ALTER TABLE `r_book_res` ADD `PREVIEW_ADDR_OUT_NET` TEXT;









