INSERT INTO pub_ddv VALUES(NULL, 1, 'pub_org', 'ORG_TYPE_ID', '机构类型1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, 2, 'pub_org', 'ORG_TYPE_ID', '机构类型2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, 3, 'pub_org', 'ORG_TYPE_ID', '机构类型3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '');

INSERT INTO pub_ddv VALUES(NULL,4,'r_book','SUBJECT_ID','语文',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,5,'r_book','SUBJECT_ID','数学',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,6,'r_book','SUBJECT_ID','英语',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,7,'r_book','SUBJECT_ID','物理',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,8,'r_book','SUBJECT_ID','化学',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,9,'r_book','SUBJECT_ID','生物',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,10,'r_book','SUBJECT_ID','地理',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,11,'r_book','SUBJECT_ID','历史',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,12,'r_book','SUBJECT_ID','政治',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,13,'r_book','SUBJECT_ID','音乐',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,14,'r_book','SUBJECT_ID','美术',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,15,'r_book','SUBJECT_ID','体育',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'');

INSERT INTO pub_ddv VALUES(NULL,16,'r_book','STU_SEG_ID','高中',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,17,'r_book','STU_SEG_ID','初中',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,18,'r_book','STU_SEG_ID','小学',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,19,'r_book','STU_SEG_ID','幼儿',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'');

INSERT INTO pub_ddv VALUES(NULL,20,'r_book','CLASS_ID','一年级',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,21,'r_book','CLASS_ID','二年级',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,22,'r_book','CLASS_ID','三年级',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,23,'r_book','CLASS_ID','四年级',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,24,'r_book','CLASS_ID','五年级',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,25,'r_book','CLASS_ID','六年级',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,26,'r_book','CLASS_ID','小班',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,27,'r_book','CLASS_ID','中班',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,28,'r_book','CLASS_ID','大班',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'');


INSERT INTO pub_ddv VALUES(NULL,29,'r_book','KIND_ID','上册',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,30,'r_book','KIND_ID','下册',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,31,'r_book','KIND_ID','中册',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'');

INSERT INTO pub_ddv VALUES(NULL,32,'sys_staff','STAFF_TYPE_ID','超级管理员',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,33,'sys_staff','STAFF_TYPE_ID','管理员',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,34,'sys_staff','STAFF_TYPE_ID','普通用户',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'');

INSERT INTO pub_press VALUES(NULL,'凤凰出版社',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,'人民教育出版社',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,'江苏教育出版社',3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'');

INSERT INTO pub_ddv VALUES(NULL, 38, 'r_book_res', 'FORMAT', '图片', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL, 39, 'r_book_res', 'FORMAT', '文档', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL, 40, 'r_book_res', 'FORMAT', '音频', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL, 41, 'r_book_res', 'FORMAT', '视频', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'');

INSERT INTO pub_server_addr VALUES(NULL, 1, '127.0.0.1', 'phoenixCloud', 'root', 'lySin@mANa84', '', '127.0.0.1', 'D:\\book\\', 'D:\\res\\', '127.0.0.1', '', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '');
INSERT INTO pub_org_cata values(NULL, '机构目录1', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '');
INSERT INTO pub_org values(null, '机构1', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '');
INSERT INTO sys_staff values(null, 1, 32, '张莉', 'zhangli', '1', '9999-01-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '');

INSERT INTO pub_ddv VALUES(NULL, 42, 'pub_hardware', 'HW_TYPE', '硬盘', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, 43, 'pub_hardware', 'HW_TYPE', '网卡', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, 44, 'pub_hardware', 'HW_TYPE', 'CPU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '');

INSERT INTO sys_purview VALUES(1,'机构管理','ORG_MANAGE',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(11,'机构菜单','ORG_MENU',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(101,'机构管理-新增','ORG_ADD',11,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(102,'机构管理-修改','ORG_UPDATE',11,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(103,'机构管理-删除','ORG_DELETE',11,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(2,'书籍管理','BOOK_MANAGE',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(21,'书籍制作菜单','BOOK_MENU',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(200,'书籍-新增','BOOK_ADD',21,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(201,'书籍-修改','BOOK_UPDATE',21,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(202,'书籍-删除','BOOK_DELETE',21,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(203,'书籍-上传附件','BOOK_UPLOAD_AFFIX',21,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(204,'书籍-编辑目录-新增','BOOK_DIR_ADD',21,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(205,'书籍-编辑目录-修改','BOOK_DIR_UPDATE',21,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'目录保存功能'),
(206,'书籍-编辑目录-删除','BOOK_DIR_DELETE',21,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(207,'书籍-编辑资源-新增','BOOK_RES_ADD',21,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(208,'书籍-编辑资源-修改','BOOK_RES_UPDATE',21,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(209,'书籍-编辑资源-删除','BOOK_RES_DELETE',21,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(210,'书籍-编辑资源-附件','BOOK_RES_UPLOAD',21,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(211,'书籍-提交审核','BOOK_ADUIT_UP',21,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'将制作状态修改为待审核状态'),
(212,'书籍-资源-提交审核','BOOK_RES_ADUIT_UP',21,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'将制作状态修改为待审核状态'),
(22,'书籍审核菜单','BOOK_ADUIT_MENU',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(213,'书籍-审核通过','BOOK_ADUIT_OK',22,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'将待审核状态修改为审核通过状态'),
(214,'书籍-审核不通过','BOOK_ADUIT_NO',22,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'将待审核状态修改为制作状态'),
(215,'书籍-资源-审核通过','BOOK_RES_ADUIT_OK',22,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'将待审核状态修改为审核通过状态'),
(216,'书籍-资源-审核不通过','BOOK_RES_ADUIT_NO',22,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'将待审核状态修改为制作状态'),
(23,'书籍发布菜单','BOOK_RELEASE_MENU',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(217,'书籍-发布','BOOK_RELEASE',23,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'将审核通过状态修改为发布状态'),
(218,'书籍-资源-发布','BOOK_RES_RELEASE',23,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'将审核通过状态修改为发布状态'),
(24,'书籍查询菜单','BOOK_QUERY_MENU',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(25,'书籍资源查询菜单','BOOK_RES_QUERY_MENU',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(3,'系统管理','SYS_MANAGE',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(31,'账号管理菜单','STAFF_MANAGE_MENU',3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(300,'账号-新增','STAFF_ADD',31,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(301,'账号-修改','STAFF_UPDATE',31,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(302,'账号-删除','STAFF_DELETE',31,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(32,'权限管理菜单','PURVIEW_MANAGE_MENU',3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(303,'权限点查询','PURVIEW_QUERY',32,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(304,'权限配置','PURVIEW_CONF',32,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(33,'硬件管理菜单','HARDWARE_MANAGE_MENU',3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(305,'硬件-增加','HARDWARE_ADD',33,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(306,'硬件-修改','HARDWARE_UPDATE',33,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(307,'硬件-删除','HARDWARE_DELETE',33,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(4,'注册码管理','REG_CODE_MANAGE',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(41,'书籍注册码菜单','BOOK_REG_CODE_MENU',4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(400,'注册码-新增','BOOK_REG_CODE_ADD',41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(401,'注册码-删除','BOOK_REG_CODE_DEL',41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'');

INSERT INTO sys_staff_purview VALUES(NULL, 1, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 1, ''),
(NULL, 1, 32, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 1, ''),
(NULL, 1, 303, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 1, ''),
(NULL, 1, 304, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 1, '');
