INSERT INTO pub_ddv VALUES(NULL, 1, 'pub_org', 'ORG_TYPE_ID', '机构类型1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, 2, 'pub_org', 'ORG_TYPE_ID', '机构类型2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, 3, 'pub_org', 'ORG_TYPE_ID', '机构类型3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '');

INSERT INTO pub_ddv VALUES(NULL,4,'r_book','SUBJECT_ID','语文',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,5,'r_book','SUBJECT_ID','数学',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,6,'r_book','SUBJECT_ID','英语',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,7,'r_book','SUBJECT_ID','物理',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,8,'r_book','SUBJECT_ID','化学',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,9,'r_book','SUBJECT_ID','生物',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,10,'r_book','SUBJECT_ID','地理',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,11,'r_book','SUBJECT_ID','历史',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,12,'r_book','SUBJECT_ID','政治',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,13,'r_book','SUBJECT_ID','音乐',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,14,'r_book','SUBJECT_ID','美术',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,15,'r_book','SUBJECT_ID','体育',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'');

INSERT INTO pub_ddv VALUES(NULL,16,'r_book','STU_SEG_ID','高中',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,17,'r_book','STU_SEG_ID','初中',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,18,'r_book','STU_SEG_ID','小学',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,19,'r_book','STU_SEG_ID','幼儿',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'');

INSERT INTO pub_ddv VALUES(NULL,20,'r_book','CLASS_ID','一年级',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,21,'r_book','CLASS_ID','二年级',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,22,'r_book','CLASS_ID','三年级',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,23,'r_book','CLASS_ID','四年级',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,24,'r_book','CLASS_ID','五年级',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,25,'r_book','CLASS_ID','六年级',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,26,'r_book','CLASS_ID','小班',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,27,'r_book','CLASS_ID','中班',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,28,'r_book','CLASS_ID','大班',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'');


INSERT INTO pub_ddv VALUES(NULL,29,'r_book','KIND_ID','上册',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,30,'r_book','KIND_ID','下册',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,31,'r_book','KIND_ID','中册',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'');

INSERT INTO pub_ddv VALUES(NULL,32,'sys_staff','STAFF_TYPE_ID','超级管理员',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,33,'sys_staff','STAFF_TYPE_ID','管理员',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,34,'sys_staff','STAFF_TYPE_ID','普通用户',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'');

INSERT INTO pub_press VALUES(NULL,'凤凰出版社',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,'人民教育出版社',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,'江苏教育出版社',3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'');

INSERT INTO pub_ddv VALUES(NULL,35,'r_book','CATA_ADDR_ID','/res/',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,36,'r_book','CATA_ADDR_ID','/resource/',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL,37,'r_book','CATA_ADDR_ID','/rs/',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'');

INSERT INTO pub_ddv VALUES(NULL, 38, 'r_book_res', 'FORMAT', '图片', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL, 39, 'r_book_res', 'FORMAT', '文档', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL, 40, 'r_book_res', 'FORMAT', '音频', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,''),
(NULL, 41, 'r_book_res', 'FORMAT', '视频', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'');

INSERT INTO pub_server_addr VALUES(NULL, 1, '127.0.0.1', 'phoenixCloud', 'root', 'lySin@mANa84', '', '127.0.0.1', 'D:\\book\\', '127.0.0.1', '', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '');
INSERT INTO pub_org_cata values(NULL, '机构目录1', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '');
INSERT INTO pub_org values(null, '机构1', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '');
INSERT INTO sys_staff values(null, 1, 32, '张莉', 'zhangli', '1', '9999-01-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '');

INSERT INTO pub_ddv VALUES(NULL, 42, 'pub_hardware', 'HW_TYPE', '硬盘', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, 43, 'pub_hardware', 'HW_TYPE', '网卡', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, 44, 'pub_hardware', 'HW_TYPE', 'CPU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '');

INSERT INTO sys_purview VALUES(NULL, '机构查询', 'queryAgency', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, '机构管理', 'manageAgency', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, '书籍查询', 'queryBook', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, '书籍编辑', 'editBook', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, '书籍审核', 'verifyBook', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, '书籍发布', 'publishBook', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, '系统管理', 'manageSystem', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, '账号查询', 'queryUser', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, '账号管理', 'manageUser', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, '权限查询', 'queryPurview', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, '权限管理', 'managePurview', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, '硬件查询', 'queryHardware', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, '硬件管理', 'manageHardware', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, '注册码查询', 'queryRegcode', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, ''),
(NULL, '注册码管理', 'manageRegcode', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '');

INSERT INTO sys_staff_purview VALUES(NULL, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 1, ''),
(NULL, 1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 1, ''),
(NULL, 1, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 1, ''),
(NULL, 1, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 1, ''),
(NULL, 1, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 1, ''),
(NULL, 1, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 1, ''),
(NULL, 1, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 1, ''),
(NULL, 1, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 1, ''),
(NULL, 1, 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 1, ''),
(NULL, 1, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 1, ''),
(NULL, 1, 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 1, ''),
(NULL, 1, 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 1, ''),
(NULL, 1, 13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 1, ''),
(NULL, 1, 14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 1, ''),
(NULL, 1, 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 1, '');